### PR TITLE
Fix that not to delete some objects after destroying functions

### LINKED ISSUE #235: Cdds[Client/Service] created in rmw_create_[client/service] not destroyed after rmw_destroy_[client/service]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - source
- Version or commit hash:
  - a07553e620eb92321949d7951b08161a65559302
- DDS implementation:
  - rmw_cyclonedds_cpp
- Client library (if applicable):
  - rcl

#### Steps to reproduce issue

```
$ colcon build --cmake-args -DCMAKE_BUILD_TYPE=Debug --packages-up-to rcl
$ . install/setup.bash
$ valgrind --leak-check=full ./build/rcl/test/test_client__rmw_cyclonedds_cpp
```

#### Expected behavior
No memory leak

#### Actual behavior
<details><summary> memory leak via valgrind </summary>
<p>

```shell
==252190== 136 (32 direct, 104 indirect) bytes in 1 blocks are definitely lost in loss record 12 of 26
==252190==    at 0x483DE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==252190==    by 0x51819DC: rmw_create_client (rmw_node.cpp:3873)
==252190==    by 0x4860929: rcl_client_init (client.c:169)
==252190==    by 0x17819C: TestClientFixture_test_client_nominal_Test::TestBody() (test_client.cpp:84)
==252190==    by 0x1B5D43: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2447)
==252190==    by 0x1AE596: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2483)
==252190==    by 0x189B3F: testing::Test::Run() (gtest.cc:2522)
==252190==    by 0x18A538: testing::TestInfo::Run() (gtest.cc:2703)
==252190==    by 0x18AC29: testing::TestCase::Run() (gtest.cc:2825)
==252190==    by 0x196312: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5216)
==252190==    by 0x1B723D: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2447)
==252190==    by 0x1AF6AA: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2483)
==252190== 
==252190== 136 (32 direct, 104 indirect) bytes in 1 blocks are definitely lost in loss record 13 of 26
==252190==    at 0x483DE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==252190==    by 0x51819DC: rmw_create_client (rmw_node.cpp:3873)
==252190==    by 0x4860929: rcl_client_init (client.c:169)
==252190==    by 0x17930D: TestClientFixture_test_client_init_fini_Test::TestBody() (test_client.cpp:153)
==252190==    by 0x1B5D43: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2447)
==252190==    by 0x1AE596: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2483)
==252190==    by 0x189B3F: testing::Test::Run() (gtest.cc:2522)
==252190==    by 0x18A538: testing::TestInfo::Run() (gtest.cc:2703)
==252190==    by 0x18AC29: testing::TestCase::Run() (gtest.cc:2825)
==252190==    by 0x196312: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5216)
==252190==    by 0x1B723D: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2447)
==252190==    by 0x1AF6AA: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2483)

```

</p>
</details>

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
Fixes #235

Signed-off-by: Chen.Lihui <lihui.chen@sony.com>

### CODE REVIEW

File: rmw_cyclonedds_cpp/src/rmw_node.cpp [hunk 1]
```diff
@@ -3827,6 +3829,8 @@ static void rmw_fini_cs(CddsCS * cs)
   dds_delete(cs->sub->rdcondh);
   dds_delete(cs->sub->enth);
   dds_delete(cs->pub->enth);
+  delete cs->sub;
+  delete cs->pub;
```
Comment (fujitatomoya) [inline rmw_cyclonedds_cpp/src/rmw_node.cpp:3833]: store NULL after `delete` to avoid double free?

File: rmw_cyclonedds_cpp/src/rmw_node.cpp [hunk 2]
```diff
@@ -3859,6 +3863,7 @@ static rmw_ret_t destroy_client(const rmw_node_t * node, rmw_client_t * client)
   }
 
   rmw_fini_cs(&info->client);
+  delete info;
```
Comment (fujitatomoya) [inline rmw_cyclonedds_cpp/src/rmw_node.cpp:3866]: same here, client->data should be null at here.

File: rmw_cyclonedds_cpp/src/rmw_node.cpp [hunk 3]
```diff
@@ -3953,6 +3959,7 @@ static rmw_ret_t destroy_service(const rmw_node_t * node, rmw_service_t * servic
   }
 
   rmw_fini_cs(&info->service);
+  delete info;
```
Comment (fujitatomoya) [inline rmw_cyclonedds_cpp/src/rmw_node.cpp:3962]: same here, service->data needs to be null.

**Review by fujitatomoya — CHANGES_REQUESTED** [review]

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos 

besides, cppcheck looks unhappy for windows and macOS. could you look into it?

File: rmw_cyclonedds_cpp/src/rmw_node.cpp (hunk 1 above)
Comment (iuhilnehc-ynos) [reply rmw_cyclonedds_cpp/src/rmw_node.cpp:3833]: Actually, rmw_cyclonedds seems not to provide extra source code to avoid double free, I followed the same style as following,

https://github.com/ros2/rmw_cyclonedds/blob/4fc5de7aa55d53d3cdd72aa9ae7d890ccdfefbe0/rmw_cyclonedds_cpp/src/rmw_node.cpp#L1349-L1350

**Comment by iuhilnehc-ynos** [comment]
@fujitatomoya 

> @iuhilnehc-ynos
> 
> besides, cppcheck looks unhappy for windows and macOS. could you look into it?

I encounter that before (in some previous PR), but It seems that maintainers not decide to deal with them.

Such as,

```
  [7.801s] 2: [src/rmw_node.cpp:704]: (error: unknownMacro) There is an unknown macro here somewhere. Configuration is required. If RCUTILS_STRINGIFY is a macro then please configure it.
```

https://github.com/ros2/rmw_cyclonedds/blob/4fc5de7aa55d53d3cdd72aa9ae7d890ccdfefbe0/rmw_cyclonedds_cpp/src/rmw_node.cpp#L704

File: rmw_cyclonedds_cpp/src/rmw_node.cpp (hunk 1 above)
Comment (iuhilnehc-ynos) [reply rmw_cyclonedds_cpp/src/rmw_node.cpp:3833]: Anyway, thanks for your suggestion, I'll update it later.

**Comment by eboasson** [comment]
> @fujitatomoya
> > @iuhilnehc-ynos
> > besides, cppcheck looks unhappy for windows and macOS. could you look into it?
> 
> I encounter that before (in some previous PR), but It seems that maintainers not decide to deal with them.

It isn't being ignored so much as that cppcheck is disagreeing with correct code and fixing it turns out to not be so trivial (see #220).

And @iuhilnehc-ynos and @fujitatomoya thank you for all the work! I look forward to the final touches on the PR so that it can be merged.

File: rmw_cyclonedds_cpp/src/rmw_node.cpp (hunk 1 above)
Comment (fujitatomoya) [reply rmw_cyclonedds_cpp/src/rmw_node.cpp:3833]: > I followed the same style as following,

i see that, i understand. but it would be better for code quality i guess.

**Comment by iuhilnehc-ynos** [comment]
@eboasson

> It isn't being ignored so much as that cppcheck is disagreeing with correct code and fixing it turns out to not be so trivial (see #220).

Thanks for your information. I'll also keep my eyes on it and try to get a method to fix it.

**Comment by iuhilnehc-ynos** [comment]
@fujitatomoya 

Could you review it again?
NOTE: Do you know why I can't use Re-review link for you?
image

**Review by fujitatomoya — APPROVED** [review]
LGTM

**Comment by fujitatomoya** [comment]
> Do you know why I can't use Re-request review link for you?

No idea, sorry...

**Comment by iuhilnehc-ynos** [comment]
I don't know if we need to explicitly add `rcutils` path to '--include-paths' for cppcheck.

- debug log

```
chenlh@lihuideMacBook-Pro rmw_cyclonedds_cpp % cd /Users/chenlh/Projects/ROS2/src/ros2/rmw_cyclonedds/rmw_cyclonedds_cpp

chenlh@lihuideMacBook-Pro rmw_cyclonedds_cpp % /Users/chenlh/Projects/ROS2/install/ament_cppcheck/bin/ament_cppcheck --xunit-file /Users/chenlh/Projects/ROS2/build/rmw_cyclonedds_cpp/test_results/rmw_cyclonedds_cpp/cppcheck.xunit.xml --include_dirs /Users/chenlh/Projects/ROS2/src/ros2/rmw_cyclonedds/rmw_cyclonedds_cpp/include
[src/rmw_node.cpp:713]: (error: unknownMacro) There is an unknown macro here somewhere. Configuration is required. If RCUTILS_STRINGIFY is a macro then please configure it.
1 errors

chenlh@lihuideMacBook-Pro rmw_cyclonedds_cpp % /Users/chenlh/Projects/ROS2/install/ament_cppcheck/bin/ament_cppcheck --xunit-file /Users/chenlh/Projects/ROS2/build/rmw_cyclonedds_cpp/test_results/rmw_cyclonedds_cpp/cppcheck.xunit.xml --include_dirs /Users/chenlh/Projects/ROS2/src/ros2/rmw_cyclonedds/rmw_cyclonedds_cpp/include /Users/chenlh/Projects/ROS2/src/ros2/rcutils/include
No problems found
```

- patch as following,

```
diff --git a/rmw_cyclonedds_cpp/CMakeLists.txt b/rmw_cyclonedds_cpp/CMakeLists.txt
index 480f1ac..08b0da0 100644
--- a/rmw_cyclonedds_cpp/CMakeLists.txt
+++ b/rmw_cyclonedds_cpp/CMakeLists.txt
@@ -105,6 +105,7 @@ register_rmw_implementation(

 if(BUILD_TESTING)
   find_package(ament_lint_auto REQUIRED)
+  set(ament_cmake_cppcheck_ADDITIONAL_INCLUDE_DIRS ${rcutils_INCLUDE_DIRS})
   ament_lint_auto_find_test_dependencies()
 endif()
```

**Comment by iuhilnehc-ynos** [comment]
- macOS

```
chenlh@lihuideMacBook-Pro rmw_cyclonedds % /usr/local/bin/cppcheck --version
Cppcheck 2.1
chenlh@lihuideMacBook-Pro rmw_cyclonedds % /usr/local/bin/cppcheck -f --inline-suppr -q -rp --suppress=internalAstError -I /Users/chenlh/Projects/ROS2/src/ros2/rmw_cyclonedds/rmw_cyclonedds_cpp/include rmw_cyclonedds_cpp/src/rmw_node.cpp
rmw_cyclonedds_cpp/src/rmw_node.cpp:713:41: error: There is an unknown macro here somewhere. Configuration is required. If RCUTILS_STRINGIFY is a macro then please configure it. [unknownMacro]
        RCUTILS_STRINGIFY(__FILE__) ":" RCUTILS_STRINGIFY(__function__) ":"
```

- ubuntu

```
chenlh@OptiPlex-7050:~/Projects/ROS2/ros2_ws_master/src/ros2/rmw_cyclonedds$ /usr/bin/cppcheck --version
Cppcheck 1.90
chenlh@OptiPlex-7050:~/Projects/ROS2/ros2_ws_master/src/ros2/rmw_cyclonedds$ /usr/bin/cppcheck -f --inline-suppr -q -rp  --suppress=internalAstError -I /home/chenlh/Projects/ROS2/ros2_ws_master/src/ros2/rmw_cyclonedds/rmw_cyclonedds_cpp/include rmw_cyclonedds_cpp/src/rmw_node.cpp
chenlh@OptiPlex-7050:~/Projects/ROS2/ros2_ws_master/src/ros2/rmw_cyclonedds$ 

```

Next step, I think I need to check `cppcheck` not `ament_cppcheck`

**Comment by iuhilnehc-ynos** [comment]
After using cppcheck(2.1) at ubuntu, it failed with the same error(unknownMacro), I believe that using concrete "-I path" for cppcheck is a feature of v2.1 compared with v1.9. (Sorry about not looking into cppcheck source.) So the patch about using 'set(ament_cmake_cppcheck_ADDITIONAL_INCLUDE_DIRS ${rcutils_INCLUDE_DIRS})' in CMakeLists.txt seems a final solution.

About `unknownMacro` issues, it's better to fix on https://github.com/ros2/rmw_cyclonedds/issues/220 .

**Comment by clalancette** [comment]
> After using cppcheck(2.1) at ubuntu, it failed with the same error(unknownMacro), I believe that using concrete "-I path" for cppcheck is a feature of v2.1 compared with v1.9. (Sorry about not looking into cppcheck source.)

Note that we have an overall problem with cppcheck 2.1: https://github.com/ros2/ros2/issues/942 .  Because of that, we are currently pinned to cppcheck 1.9 on all platforms.

**Comment by iuhilnehc-ynos** [comment]
> pinned to cppcheck 1.9

That's good to know.

**Comment by iuhilnehc-ynos** [comment]
@eboasson 

> I look forward to the final touches on the PR so that it can be merged.

Could you please review it? (I hope you got a happy mood.)

File: rmw_cyclonedds_cpp/src/rmw_node.cpp [hunk 4]
```diff
@@ -3827,6 +3829,14 @@ static void rmw_fini_cs(CddsCS * cs)
...
   dds_delete(cs->sub->enth);
   dds_delete(cs->pub->enth);
+  if (cs->sub) {
+    delete cs->sub;
+    cs->sub = NULL;
+  }
+  if (cs->pub) {
+    delete cs->pub;
+    cs->pub = NULL;
+  }
```
Comment (eboasson) [inline rmw_cyclonedds_cpp/src/rmw_node.cpp:3839]: Just above it already dereference `cs->sub`, so we know that it is not a null pointer (same for `cs->pub`) and after checking the call sites, I do believe that it only calls `rmw_fini_cs` with a fully initialised `CddsCS`. That said, I think it is a good idea to check. But then is should be:

```suggestion
  if (cs->sub) {
    dds_delete(cs->sub->rdcondh);
    dds_delete(cs->sub->enth);
    delete cs->sub;
    cs->sub = NULL;
  }
  if (cs->pub) {
    dds_delete(cs->pub->enth);
    delete cs->pub;
    cs->pub = NULL;
  }
```

**Review by eboasson — COMMENTED** [review]
Hi @iuhilnehc-ynos there are three things:
* I am embarrassed by the number of memory leaks
* In the long run, it would probably be worth it to rely more heavily on `unique_ptr`s
* And there's one thing I suggest changing in the PR, it doesn't actually fix anything but I think it may help in the future.

Thank you!

File: rmw_cyclonedds_cpp/src/rmw_node.cpp (hunk 4 above)
Comment (iuhilnehc-ynos) [reply rmw_cyclonedds_cpp/src/rmw_node.cpp:3839]: Thanks for your suggestions. I believe you're right.
Actually, I also prefer using `unique_ptr`. I'll update it that makes us clearly.

**Comment by iuhilnehc-ynos** [comment]
@eboasson 

> In the long run, it would probably be worth it to rely more heavily on unique_ptrs

I used the `unique_ptr` if it could be.

> there's one thing I suggest changing in the PR

After using `unique_ptr`, it seems not necessary to change with the suggestion.

Could you please review it again? Thank you.

**Review by eboasson — APPROVED** [review]
@iuhilnehc-ynos it looks good to me, thank you! @ivanpauno or @hidmic I'd appreciate it if you could take a final look because I don't quite trust myself with C++ just yet ...

File: rmw_cyclonedds_cpp/src/rmw_node.cpp [hunk 5]
```diff
@@ -3835,30 +3835,34 @@ static rmw_ret_t destroy_client(const rmw_node_t * node, rmw_client_t * client)
...
-      node->name, node->namespace_));
-    rmw_dds_common::msg::ParticipantEntitiesInfo msg =
-      common->graph_cache.dissociate_reader(
-      info->client.sub->gid, common->gid, node->name,
-      node->namespace_);
-    if (RMW_RET_OK != rmw_publish(
-        common->pub,
-        static_cast<void *>(&msg),
-        nullptr))
+  if (client->data) {
```
Comment (ivanpauno) [inline rmw_cyclonedds_cpp/src/rmw_node.cpp:3840]: why this check?

**Review by ivanpauno — APPROVED** [review]
lgtm with one minor question

File: rmw_cyclonedds_cpp/src/rmw_node.cpp (hunk 5 above)
Comment (iuhilnehc-ynos) [reply rmw_cyclonedds_cpp/src/rmw_node.cpp:3840]: check the pointer before using it and also avoid double free for it

**Review by ivanpauno — APPROVED** [review]

**Comment by ivanpauno** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12287/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7260/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10004/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12186/)
