### PR TITLE
Fix MSBuild warnings C4146 and C4267

### LINKED ISSUE #90: MSBuild warnings in serdata.cpp
## Bug report

**Required Info:**
Building on Windows 10, 1903 in a docker container with the latest VCTools (16.24) installed from VS BuildTools.
https://citest.ros2.org/job/nightly_win_extra_rmw_rel/10/warnings43Result/

I get a couple of MSBuild warnings, 
serdata.cpp:115
```
'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data
```
Looks to be introduced in https://github.com/ros2/rmw_cyclonedds/pull/77

serdata.cpp:506
```
unary minus operator applied to unsigned type, result still unsigned
```
Introduced in https://github.com/ros2/rmw_cyclonedds/pull/75

@rotu

### PR DESCRIPTION
**Pull request by emersonknapp**
Closes #90 
Closes https://github.com/ros-tooling/aws-oncall/issues/66

Signed-off-by: Emerson Knapp <emerson.b.knapp@gmail.com>

### CODE REVIEW

**Comment by emersonknapp** [comment]
myself - please run this CI job
Gist: https://gist.githubusercontent.com/emersonknapp/a65f8b1f5e441f692fe333a9d12b42c0/raw/d66d8d4ca569892224ca2f8dcf6cc8c5cb210e97/ros2.repos
BUILD args: --packages-up-to rmw_cyclonedds_cpp
TEST args: --packages-select rmw_cyclonedds_cpp
Job: ci_launcher

**Comment by emersonknapp** [comment]
Windows packaging job first before full run

[Build Status](https://ci.ros2.org/job/ci_packaging_windows/140/)

**Comment by emersonknapp** [comment]
Full run 

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9280/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4967/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7593/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9201/)
* Windows-container [Build Status](http://ci.ros2.org/job/ci_windows-container/86/)

**Comment by nuclearsandwich** [comment]
> EDIT: The CI builds are hardcoded internally to explicitly ignore `rmw_cyclonedds_cpp` so they are failing trying to find it - @nuclearsandwich any advice on that?

For RMW implementations specific Jenkins parameters need to be enabled.
When using ci_launcher you can enable or disable specific RMW and the disabled ones will be ignored. In this case there was a mismatch between the enabled RMW and the selected packages. I've re-triggered the launcher job above with CI_USE_CYCLONEDDS enabled.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9285/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4972/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7598/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9206/)
* Windows-container [Build Status](http://ci.ros2.org/job/ci_windows-container/95/)

**Comment by emersonknapp** [comment]
Ohh I forgot about the checkboxes, thank you!

File: rmw_cyclonedds_cpp/src/serdata.cpp [hunk 1]
```diff
@@ -504,7 +504,7 @@ void serdata_rmw::resize(size_t requested_size)
 
   /* FIXME: CDR padding in DDSI makes me do this to avoid reading beyond the bounds
   when copying data to network.  Should fix Cyclone to handle that more elegantly.  */
-  size_t n_pad_bytes = (-requested_size) % 4;
+  size_t n_pad_bytes = 4 - (requested_size % 4);  // Same as (-x) % 4, without negating unsigned
```
Comment (eboasson) [inline rmw_cyclonedds_cpp/src/serdata.cpp]: Thanks for fixing helping out and addressing the warnings — but beware: this is not equivalent to the original. If you assume ``requested_size`` is 0, then the original trivially evaluates to 0 and the proposed to 4. The damage will be very minor because — I suppose all — DDS implementations will ignore the additional bytes at the end of the serialised data, but it is a waste to add 4 bytes to any sample that happens to have a serialised size that is a multiple of 4 bytes.

 There are various solutions. I think I'd go for defining ``aligned_size = (requested_size + 3) & ~3``, and then replacing ``requested_size+n_pad_bytes`` to ``aligned_size`` and the bare ``n_pad_bytes`` in the ``memset`` with ``aligned_size-requested_size``.

Other reasonable choices would be to use ``(0-requested_size)%4`` or ``(4-(requested_size%4))%4``, or …

I guess one would need to verify which MS's compiler finds acceptable …

Comment (emersonknapp) [reply rmw_cyclonedds_cpp/src/serdata.cpp]: Updated to try one of the versions
Windows Packaging: [Build Status](https://ci.ros2.org/job/ci_packaging_windows/141/)

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9295/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4980/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7608/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9219/)
* Windows-container [Build Status](http://ci.ros2.org/job/ci_windows-container/103/)

**Comment by emersonknapp** [comment]
@eboasson addressed by using one of your suggestions, MSBuild seems happy with `0 - x`, good idea. The OSX builds are failing across the board for infrastructural reasons, so if the `Windows-container` build passes I'd propose we merge.

**Comment by emersonknapp** [comment]
Great! Do you have merge access? I do not for this repository.

**Comment by eboasson** [comment]
@emersonknapp, I do (I'm the original author of the repository, even if it was @rotu who did the hard work of making the serializer perform well).

**Comment by emersonknapp** [comment]
Thanks!
